kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-default
spec:
  repo: https://github.com/encodeflush/fleet-apps
  branch: main
  paths:
  - single-cluster/helm-multi-chart
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
